name: First workflow

on:
  push:
    branches: [actions]
    tags: [v*]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout vcpkg
        uses: actions/checkout@v2
        with:
          repository: Microsoft/vcpkg
          path: '.\vcpkg'
      - name: Bootstrap vcpkg
        run: 'cd vcpkg; .\bootstrap-vcpkg.bat'
      - name: Install curl
        run: '.\vcpkg install curl:x86-windows curl:x64-windows'
