name: First workflow

on:
  push:
    branches: [actions]
    tags: [v*]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Dump environment variables
        run: 'ls env: | foreach { ''{0}={1}'' -f $_.Key,$_.Value }'
        
      - run: vcpkg install curl:x86-windows curl:x64-windows
      
      - uses: actions/checkout@v2
          
      - name: Copy libcurl dlls
        run: >-
          @('x86', 'x64') | foreach {
            mkdir "runtimes/win-$_/native";
            cp "$Env:VCPKG_ROOT/installed/$_-windows/bin/*.dll" "runtimes/win-$_/native"
          }
