name: First workflow

on:
  push:
    branches: [actions]
    tags: [v*]

jobs:
  build:
    runs-on: windows-latest
    env:
      VCPKG: ${{ env.VCPKG_INSTALLATION_ROOT }}
    steps:
      - name: Dump environment variables
        run: 'ls env: | foreach { ''{0}={1}'' -f $_.Key,$_.Value }'
        shell: pwsh
      
      - uses: actions/cache@v1
        id: vcpkg-installation-root-cache
        with:
          path: ${{ env.VCPKG }}/installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('${{ env.VCPKG }}/ports/curl/CONTROL') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-
        
      - run: vcpkg install curl:x86-windows curl:x64-windows
        if: steps.vcpkg-installation-root-cache.outputs.cache-hit != 'true'
      
      - uses: actions/checkout@v2
          
      - name: Copy libcurl dlls
        run: |
          @('x86', 'x64') | foreach {
            mkdir "runtimes/win-$_/native";
            cp "$Env:VCPKG_INSTALLATION_ROOT/installed/$_-windows/bin/*.dll" "runtimes/win-$_/native"
          }
        shell: pwsh
